###############################################################
# Terraform Settings
###############################################################

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google" # Google Cloud provider
      version = ">= 7.0.0"         # Require version 7.0.0 or newer
    }
  }
}

# Note: The Google provider block will be generated by Terragrunt.
# Authentication can be handled via GOOGLE_APPLICATION_CREDENTIALS
# or gcloud CLI with "gcloud auth application-default login".

###############################################################
# Google Cloud Run Service
###############################################################

resource "google_cloud_run_v2_service" "svc" {
  name     = var.app_name     # Cloud Run service name
  location = var.gcp_region   # Region for the service

  deletion_protection = false # Allow deletion for demos/testing

  # Define the container(s) for the service
  template {
    containers {
      image = var.gcp_container_image # Container image from Artifact Registry/Docker Hub
      # Example default: "us-docker.pkg.dev/cloudrun/container/hello"
    }
  }
}

###############################################################
# IAM Binding: Make Cloud Run Service Public
###############################################################

resource "google_cloud_run_v2_service_iam_member" "public" {
  name     = google_cloud_run_v2_service.svc.name     # Reference the Cloud Run service
  location = google_cloud_run_v2_service.svc.location # Same region
  project  = google_cloud_run_v2_service.svc.project  # Same project

  role   = "roles/run.invoker" # Role required to invoke a Cloud Run service
  member = "allUsers"          # Grants access to anyone with the URL
}
